kind: pipeline
name: default

# build from heavy image
steps:
  - name: build
    image: docker.uclv.cu/node
    failure: ignore
    commands:
      - yarn global add pegjs
      - yarn install
      - yarn build

  - name: run
    image: docker.uclv.cu/node:alpine
    commands:
      - node dist/main.js

