kind: pipeline
name: default

steps:
- name: build
  image: docker.uclv.cu/node
  commands:
  - yarn install
  - yarn build
  
- name: run
  image: docker.uclv.cu/node:alpine
  commands:
  - node dist/main.js